language: node_js
node_js:
- '6'
script: npm test
install:
- npm install
deploy:
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-development
  on:
    branch: development
- provider: script
  skip_cleanup: true
  script: npm run deploy-bib-qa
  on:
    branch: qa
env:
  global:
  - secure: j6SsIFCChI4N3wSwWtlGSKz7e/5vxgUgmVasDurh/EwTZrXO0fPyFRY8b6fr3S/DVOPAR0B2WPxjmc/W0I8fdzP4R9uZxgYXB9y1D1TPG116PBf5V46refR9D+Sf8BFk6CEvGRdJ+HUw74YBXgj9xHAFDKKmUQzcVIeQsEceKbq9nrlKcMvhGzHo5O6YkEDzmPSskXpegtCvEFa9Ya1P9tZ7kh/kDOuXiWP6Ol3hmNt0NxSl6mbWJ0Fa0WFeTIxVd+9InGMZJJGukhrRdNsiBdroqxK00wnnyx4AAmktGzN6r+Bup9tmIFNywfUkZK4A3b9j68hwjEVbf0x/xqRmPlTnEv6bC4U6j8twrPA7N2JuejhDk2/D41ilNOGFtRDIZ64jJMXtJM2yKfhBIgwU2I8KTi0oN+8DBv4C3K9ZhPNgE3+Jm9sRNrjSHFvILI6fGGdJTvmlnfPZ4VfU5p9Vqq86WyZHm6GunIImKgpWCKju+wZJpRMbezYIy5yRM4Vbge/jHnK+tK0Slcqb7IwcstbD0/emKN1E/WOQQlppRsHMPfAtB9r9GgQfKquxweWnyHYnyHn+fYf5Nw2GYmJ9bL8EmUh2cUE/YGNrwKfb/kj2p4664sYpFSTh6mM0wxB6bk0qbd67Cet9HL1MZn3xHbi/mLHEdjIbYiyIxhFQNPQ=
  - secure: XLsYAvEIVkrEiljZvj3HKhbdQBDi5ialoo4xB8N72xX5De0+NEj0PHQpe9zv1KOjs6TCjO1U9RNVIsxfk8VE237agXLInzukvxPLntulOZyv7HnozvS1G1vGCZxkkwg2JcFItMHJIg7O2RjknmRLBeuvYwQmEdYCOajSUFTeY+BY/mPvJh12czZfbEMYp0U0z0o0oQZR3LJs0wMySDjE1LK5xROpldHUysKo+cUg7cVTpwe2bVtK9yb0NNcGKEAb7NKZyHkA2YtR3WZmpY7Td0T07DAWxw7gopg1bup49r8Rg+VF94uu+kUrm9aX5ARF1npB0YjC+ovsT5gNtn1AxDLorSKMCY3tx4i35MHkqCu02+9siSMdy7PtCMcI57V2tzWDfrmmxGGS+s3mcWQa1fsOxoA0v1NiAgdF78aGjZ8TeuG+yT1H8vt5cQp7gx5RfiSxxzxW5XnWgtku6G2//F+F3bYJi5rlZccXTBFFYu8KOKmOJfrAz3cgKom5wozGHCCu/s4mFKeumYb7Xyg3xxzOu+5jGAORA0TmeWIi63Zk7Rv1znbZasmdcGNhDq3nMN8kJOav2HsyIruvwdZXLdypQc1qooT471Agn8Mcq7AXfOMGoB6nIFOnUdU+gIW/3iwHXsIu5rJn0bZhFA84r3NHpnbkb/l2EQMgeQV6/FM=
  - secure: IgyqIuUQXg73Q/svG6Diot7qKwrE/tjSVZlC/6AcYrL6PmT9m49C7cAl0EzalGELFD2IpXhhn7BCssjC/A+ccVACNu0MEI0ykWpG67/jyChhkhZE9FgWK8/eJV6tKGLQ0T7SlVUgJs384T53aNyNY6A7rz/1ib34dHAsD8M8QD2PdWqyYcWQzr+pMBsyoFBoVRzaEP7szdZf8aHBTIRcfJ/YGHlAUtWfjb2wQevU29Fzfir2/nIKEmuPqPUv0D3KcGOFIMgRct21HCnsqxuDpM0no8XFaMUjGSE/IsA1psAJFGazCnntl919IxgL9dLpaoZ6lCDm8pLBxatNUQEd1aWuHHc7IEwd2AClSwwZfvKLq2JZnHeUlVitwMgXtcbRDvQr2SFCE9K92kKlpy0nrpNfmLx56Aw5OEQQJKpBwjPRqyuiaQbZjPTjRHKPaXn+xdQzqANe1qEtytTgd65fbQkf7aZqv9JVF43erxgZSiMB5SeS/yxPjLZzAvvr4DlU+YJR1hT+4ttFeaQTCqJIp203XGeIvdlXV2taES309ngipcRJwHcdcowhAwLY2KhIiRRYPtWsAVrefJMfgc27v/bZpkAt+6EPC67c1lmB6dTGjEoNBU9aQ5s10KblFymbvHp3yTQNfidDLBxI1ve6TiiXRnyXCbTY4hTXuUfKwjs=
